apiVersion: v1
kind: Secret

metadata:
  name: jerney-secret
  namespace: jerney-ns
  labels:
    app.kubernetes.io/part-of: jerney

type: Opaque
data:
  POSTGRES_USER: amVybmV5X3VzZXI=  # Base64 encoded value of 'jerney_user'
  POSTGRES_PASSWORD: amVybmV5X3Bhc3NfMjAyNg==  # Base64 encoded value of 'jerney_pass_2026'
  DB_USER: amVybmV5X3VzZXI=  # Base64 encoded value of 'jerney_user'
  DB_PASSWORD: amVybmV5X3Bhc3NfMjAyNg==  # Base64 encoded value of 'jerney_pass_2026'
