apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: jerney-ns
  labels:
    app.kubernetes.io/part-of: jerney
    app.kubernetes.io/name: backend-service
    app.kubernetes.io/component: backend

spec:
  selector:
    app.kubernetes.io/name: backend-deployment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000


